name: Test Action in Marketplace
on: [workflow_dispatch]           
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run my own container action
        id: action
        uses: youngsend/MyActionInAction@v1.0.0
        with:
          who-to-greet: '@youngsend'
          
      - name: Output the answer
        run: echo "The answer is ${{ steps.action.outputs.answer }}"
